### ISSUE TITLE
Discussion Zone for custom templates

### ISSUE THREAD

**Issue by alain01** [mambax7/publisher#20]
Hi,
This is not an issue, just a mini forum.
If there is a place for that, please show me the URL.

Ok,
You work is fine, it's run very well.
Category 1: used the  publisher_custom1.tpl template
Category 1: used the  publisher_custom2.tpl template
I got the boths articles : 

10 Numbers rating - CUSTOM 1 
Article 2 (Like/Dislike rating) - CUSTOM 2 
Good job.

Now some questions : 
1 - I Add a 3th template in the /themes/xswatch4/modules/publisher/custom directory 
But i dont see it in the categories tab.
I try with the name: 
publisher_category_custom.tpl
publisher_custom3.tpl

In the list there just publisher_custom1.tpl and publisher_custom1.tpl.
I missed someting ?

2 - With these 2 templates, what do you waiting for me about that ?
That I customize theses templates to see a real difference in presentation ?

**Comment by alain01** [comment]
3 - Missed index.php in the publisher\templates_bootstrap\bootstrap4\publisher\custom directory

**Comment by mambax7** [comment]
Reg. (1) My mistake in explaining it. 
You don't add these templates to your theme, but to the module's /custom folder

Reg. (2) - actually there is nothing to do, just test it and see how it works for you

Reg. (3) These folders will be removed as I used them for testing, but they are not needed, since the templates will be in the module's /custom folder
.

**Comment by alain01** [comment]
Ok ! 
I'm close to finish to edit the publisher_custom2.tpl template in full bootstrap 4

**Comment by mambax7** [comment]
Great! You can call the file: publisher_custom_test_xswitch4.tpl

This way people know they can test it in xSwatch4 theme.

**Comment by alain01** [comment]
ok
