### ISSUE TITLE
Sentence

### ISSUE THREAD

**Issue by aerograf** [mambax7/publisher#9]
Proposal for the expansion of the functional:
1. The ability to make a separate page with the ability to place it somewhere on the site (not a block, because the option offered by items_spot does not quite fit. Several templates are used, and if this block and templates are used, then other options stop working.)
2. Ability to associate with NewBB
3. The ability to link with extgallery, with the insert function from the image gallery.

**Comment by aerograf** [comment]
4. The ability to disable the main page to show a list of articles or a list of categories.

**Comment by mambax7** [comment]
I'll be looking into it, but I need more information about each of the features.  And could you please split them into individual requests? 
1) I'm not sure how you want to do it: we can only put pages as part of the main content block. Do you want to be able to place a page in a block? 

2) what kind of association? Do you want to to create a new article in Publisher from within the NewBB? 

3) Do you want to add a picture in Publisher from a extGallery instead of the ImageManager? 

4) Do you want to have an option to display only one article, without an list?

Thanks!

**Comment by aerograf** [comment]
It seems to me that the above is no longer relevant
